config/routes.rb
Rails.application.routes.draw do
  
  get 'stockcsvs/index'

  get 'stockcsvs/import'

  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :user_stocks, except: [ :show, :edit, :update]
  get 'welcome/index'
  root 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stocks', to:"stocks#search"
  resources :stockcsvs do
    collection { post :import }
  end
  get 'stockcsv', to:"stockcsv#index"

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
   

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

	has_many :user_stocks
	has_many :users ,through: :user_stocks
	def self.find_by_ticker(ticker_symbol)
		where(ticker: ticker_symbol).first
	end

	def self.new_from_lookup(ticker_symbol)
		looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
		return nil unless looked_up_stock.name

		new_stock = new(ticker: looked_up_stock.symbol,name: looked_up_stock.name)
		new_stock.last_price = new_stock.price
		new_stock
	end

	def price
		closing_price = StockQuote::Stock.quote(ticker).close
		return "#{closing_price}(closing)" if closing_price

		opening_price = StockQuote::Stock.quote(ticker).open
		return "#{opening_price} (opening)" if opening_price
		'unavailable'
	end 
end

app/models/stockcsv.rb
class Stockcsv < ApplicationRecord
	require 'csv'

  def self.import(file)

    CSV.foreach(file.path, headers: true) do |row|

      stockcsv_hash = row.to_hash # exclude the price field
      stockcsv = Stockcsv.where(id: stockcsv_hash["id"])

      if stockcsv.count == 1
        stockcsv.first.update_attributes(stockcsv_hash)
      else
        Stockcsv.create!(stockcsv_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)
end # end class

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  def full_name
  	return "#{first_name} #{last_name}".strip if (first_name || last_name)
  	"Anonymous"
  end

  def can_add_stock?(ticker_symbol)
  	under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

	def under_stock_limit?
		(user_stocks.count < 10)
	end

	def stock_already_added?(ticker_symbol)
		stock = Stock.find_by_ticker(ticker_symbol)
	return false unless stock

	user_stocks.where(stock_id: stock.id).exists?
	end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
	belongs_to :user
	belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stockcsvs_controller.rb
class StockcsvsController < ApplicationController
   def index
    @stockcsvs = Stockcsv.all
  end

  def import

    Stockcsv.import(params[:file])
    redirect_to root_url, notice: "imported."
    rescue
      redirect_to root_url, notice: "Invalid CSV file format."
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	def search
		if params[:stock]
			@stock = Stock.find_by_ticker(params[:stock])
			@stock ||=Stock.new_from_lookup(params[:stock])
		end

    if @stock
        	#render json: @stock
      render partial:'lookup'
		else
	    	render status: :not_found, nothing: true
	    end
	end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	before_filter :configure_permitted_parameters

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
	end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :set_user_stock, only: [:show, :edit, :update, :destroy]

  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user_stocks = UserStock.all
  end

  # GET /user_stocks/1
  # GET /user_stocks/1.json
  def show
  end

  # GET /user_stocks/new
  def new
    @user_stock = UserStock.new
  end

  # GET /user_stocks/1/edit
  def edit
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    if params[:stock_id].present?
      @user_stock = UserStock.new(stock_id: params[:stock_id], user: current_user)
    else
      stock = Stock.find_by_ticker(params[:stock_ticker])
      if stock
        @user_stock = UserStock.new(user: current_user, stock: stock)
      else
        stock = Stock.new_from_lookup(params[:stock_ticker])
        if stock.save
          @user_stock = UserStock.new(user: current_user, stock: stock)
        else
          @user_stock = nil
          flash[:error] = "Stock is not available"
        end
      end
    end
    respond_to do |format|
      if @user_stock.save
        format.html { redirect_to my_portfolio_path, notice: "Stock #{@user_stock.stock.ticker} was successfully added" }
        format.json { render :show, status: :created, location: @user_stock }
      else
        format.html { render :new }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stocks/1
  # PATCH/PUT /user_stocks/1.json
  def update
    respond_to do |format|
      if @user_stock.update(user_stock_params)
        format.html { redirect_to @user_stock, notice: 'User stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_stock }
      else
        format.html { render :edit }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock.destroy
    respond_to do |format|
      format.html { redirect_to my_portfolio_path, notice: 'Stock was successfully removed from portfolio.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_stock
      @user_stock = UserStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_stock_params
      params.require(:user_stock).permit(:user_id, :stock_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def my_portfolio
		@user_stocks = current_user.stocks
		@user = current_user
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stockcsvs_helper.rb
module StockcsvsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_spinner.html.haml
#spinner.row.col-md-12.text-center.spinner{:style => "display: none;"}
  %i.fa.fa-spinner.fa-spin.fa-2x
  Processing...

app/views/layouts/_navigation.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    = link_to 'Finance Tracker', root_path, class: "navbar-brand"
    - if current_user
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav.col-md-6
          %li
            = link_to "My Portfolio", my_portfolio_path
          %li
            = link_to "My Profile", edit_registration_path(current_user)
          %li
            = link_to "Link3", "/path3"
        %ul.nav.navbar-right.col-md-4
          %li.col-md-8.user-name.text-right
            %i.fa.fa-user
            = current_user.full_name.present? ? current_user.full_name : current_user.email
          %li.col-md-4.logout
            = link_to("Logout", destroy_user_session_path,     |
            class: 'btn btn-xs btn-danger', method: :delete) |

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "FinanceTracker"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    = render 'layouts/navigation'
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      %footer
        %p © Company 2016

app/views/stockcsvs/import.html.haml
%h1 Stockcsvs#import
%p Find me in app/views/stockcsvs/import.html.haml

app/views/stockcsvs/index.html.haml
= flash[:notice]
%table
  %thead
    %tr
      %th Id
      %th.col-md-4 symbol
      %th.col-md-4 name
      %th.col-md-4 price
  %tbody
    - @stockcsvs.each do |stockcsv|
      %tr
        %td= stockcsv.id
        %td.col-md-4= stockcsv.symbol
        %td.col-md-4= stockcsv.name
        %td.col-md-4= stockcsv.price
        
%div
  %h3 Import a CSV File
  = form_tag import_stockcsvs_path, multipart: true do
    = file_field_tag :file
    %br
    = button_tag(type: :submit, class: 'btn btn-lg btn-success') do
      Import csv file

app/views/stocks/_list.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Symbol
      %th Current Price
      - if @user.id == current_user.id
        %th Actions
  %tbody
    - @user_stocks.each do |user_stock|
      %tr
        %td= user_stock.name
        %td= user_stock.ticker
        %td= user_stock.price
        - if @user.id == current_user.id
          %td
            = link_to 'Delete',                         |
              user_stock_path(user_stock),              |
              :method => :delete,                       |
              :data => { :confirm => 'Are you sure?' }, |
              :class => 'btn btn-xs btn-danger'         |

app/views/stocks/_lookup.html.haml
#stock-lookup
  %h3 Search for Stocks
  = form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do
    .form-group.row.no-padding.text-center.col-md-12
      .col-md-10
        = text_field_tag :stock,                    |
        params[:stock],                           |
        placeholder: 'Stock Ticker Symbol',       |
        autofocus: true,                          |
        class: 'form-control search-box input-lg' |
      .col-md-2
        = button_tag(type: :submit, class: 'btn btn-lg btn-success') do
          %i.fa.fa-search
          Look up a stock
      = render 'common/spinner'
      - if @stock
        #stock-lookup-results.well.results-block
          %strong Symbol:
          = @stock.ticker
          %strong Name:
          = @stock.name
          %strong Price:
          = @stock.price
          - if current_user.can_add_stock?(@stock.ticker)
            = link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker, |
            stock_id: @stock.id ? @stock.id : ''), class: 'btn btn-xs btn-success', method: :post         |
          - else
            %span.label.label-default
              Stock cannot be added because you have already added
              - if !current_user.under_stock_limit?
                10 stocks
              - if current_user.stock_already_added?(@stock.ticker)
                this stock

    #stock-lookup-errors

app/views/user_stocks/_form.html.haml
= form_for @user_stock do |f|
  - if @user_stock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_stock.errors.count, "error")} prohibited this user_stock from being saved:"
      %ul
        - @user_stock.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :stock_id
    = f.number_field :stock_id
  .actions
    = f.submit 'Save'

app/views/user_stocks/edit.html.haml
%h1 Editing user_stock

= render 'form'

= link_to 'Show', @user_stock
\|
= link_to 'Back', user_stocks_path

app/views/user_stocks/index.html.haml
%h1 Listing user_stocks

%table
  %thead
    %tr
      %th User
      %th Stock
      %th
      %th
      %th

  %tbody
    - @user_stocks.each do |user_stock|
      %tr
        %td= user_stock.user_id
        %td= user_stock.stock_id
        %td= link_to 'Show', user_stock
        %td= link_to 'Edit', edit_user_stock_path(user_stock)
        %td= link_to 'Destroy', user_stock, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User stock', new_user_stock_path

app/views/user_stocks/new.html.haml
%h1 New user_stock

= render 'form'

= link_to 'Back', user_stocks_path

app/views/user_stocks/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_stock.user_id
%p
  %b Stock:
  = @user_stock.stock_id

= link_to 'Edit', edit_user_stock_path(@user_stock)
\|
= link_to 'Back', user_stocks_path

app/views/users/my_portfolio.html.haml
= render 'stocks/lookup'
= render 'stocks/list'

app/views/welcome/index.html.haml
%h1 Welcome to finance tracker APP
= link_to "logout",destroy_user_session_path ,:method => :delete